/**
 * POST /api/ai/reply-draft — streams an AI-generated reply draft.
 *
 * Body: `{ emailId: string, context?: string }`
 *
 * Fetches the email and the last 5 thread messages, calls emailAI.draftReply(),
 * and streams the response as plain text (suitable for reading with a
 * ReadableStreamDefaultReader or EventSource).
 */

import { auth } from "@/auth";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { emailAI } from "@/lib/ai/email-ai";
import { ValidationError, NotFoundError } from "@/lib/errors";

/** Maximum number of thread messages sent as context to Claude. */
const THREAD_CONTEXT_LIMIT = 5;

const replyDraftSchema = z.object({
  emailId: z.string(),
  context: z.string().optional(),
});

/**
 * POST /api/ai/reply-draft
 * Streams the reply draft generated by Claude as raw text chunks.
 */
export async function POST(request: Request): Promise<Response> {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body: unknown = await request.json();
  const parsed = replyDraftSchema.safeParse(body);
  if (!parsed.success) {
    const err = new ValidationError("Invalid request body", {
      issues: parsed.error.flatten(),
    });
    return Response.json(
      { error: err.message, details: parsed.error.flatten() },
      { status: 400 },
    );
  }

  const email = await prisma.cachedEmail.findFirst({
    where: {
      id: parsed.data.emailId,
      account: { userId: session.user.id },
    },
  });

  if (!email) {
    const err = new NotFoundError("Email", parsed.data.emailId);
    return Response.json({ error: err.message }, { status: 404 });
  }

  // Fetch last N thread messages for context
  const threadMessages = await prisma.cachedEmail.findMany({
    where: {
      threadId: email.threadId,
      accountId: email.accountId,
    },
    orderBy: { date: "desc" },
    take: THREAD_CONTEXT_LIMIT,
  });

  const messagesForAI = threadMessages
    .reverse()
    .map((msg) => ({
      from: msg.fromAddress,
      textBody: msg.bodyText ?? msg.bodyHtml?.replace(/<[^>]+>/g, " ") ?? null,
      receivedAt: msg.receivedAt,
    }));

  // Add optional user-supplied context as a final message
  const contextNote = parsed.data.context
    ? [
        {
          from: null,
          textBody: `User instruction: ${parsed.data.context}`,
          receivedAt: new Date(),
        },
      ]
    : [];

  const stream = new ReadableStream({
    async start(controller) {
      try {
        const draft = await emailAI.draftReply({
          threadMessages: [...messagesForAI, ...contextNote],
          styleExemplars: [],
          tone: "professional",
        });
        controller.enqueue(new TextEncoder().encode(draft));
      } catch (err) {
        controller.enqueue(
          new TextEncoder().encode(
            err instanceof Error ? err.message : "Draft generation failed.",
          ),
        );
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
